# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  summarization:
    class: SummarizationJob
    queue: summarization
    schedule: every minute
  schedule_rollover:
    class: ScheduleRolloverJob
    queue: default
    schedule: every minute
  stt_chunk_sweeper:
    command: "SttChunkStorage.sweep!"
    schedule: every hour at minute 42

production:
  summarization:
    class: SummarizationJob
    queue: summarization
    schedule: every minute
  schedule_rollover:
    class: ScheduleRolloverJob
    queue: default
    schedule: every minute
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every 10 minutes
  embedding_backfill:
    class: EmbedBackfillJob
    queue: default
    schedule: every 10 minutes
  stt_chunk_sweeper:
    command: "SttChunkStorage.sweep!"
    schedule: every hour at minute 42

